### PR TITLE
Make responsive, remove extraneous font refs, add video icons, CSS refactor

### LINKED ISSUE #19: video files don't have a proper icon
Currently video files have a generic "file" icon, they should have an icon that indicates that they are videos.

### LINKED ISSUE #23: Font source target is invalid
The embedded style references a handful of fonts via a relative and nonexistant path `../fonts/`
For instance `font-family:'Glyphicons Halflings';src:url(../fonts/glyphicons-halflings-regular.eot);`
This specifically causes issues when doing something like `wget -r http://gateway/ipfs/Qm...` presenting a bunch of 404's up front.

I'm not familiar enough with CSS to know, but is there any analog to the HTML `<base>` tag?
Specifically, I'm wondering if there's a way to hash these fonts and make the source target relative to the gateway root.
i.e. `src:url(${gatewayroot}/ipfs/Qm.../font.eot)`

If not, I suppose it would be best to just remove them.

### LINKED ISSUE #24: Make table responsive
The dir-index is looking good when viewed on a computer or laptop. However, when using a smartphone the dir-index does not adapt to the small screen and you have to zoom-in and zoom-out to view and click on directory entries.

As a solution to this I recommend to use HTML5 and responsive Web design.

### PR DESCRIPTION
**Pull request by jessicaschilling**
- Removes extraneous references to Glyphicons (closes #23)
- Makes page responsive overall (closes #24)
- Adds file icons for .wmv, .mov, .mkv (closes #19)
- Strips out most of the CSS, which looks like it was originally cloned from an early version of Bootstrap but no longer needed
- Makes colors consistent with those in ipfs-css
- Tidies up in general

### CODE REVIEW

**Comment by jessicaschilling** [comment]
Question for @Stebalien -- What's the best way to test this in situ? At the moment I'm just looking at changes reflected in the unpopulated template, and I don't totally trust that. Thanks!

**Comment by jessicaschilling** [comment]
@Stebalien, if you don't mind having a look, would much appreciate! Thanks.

**Comment by Stebalien** [comment]
Look:

* The filename links kind of blend-in with the new color scheme.
* In general, I'm not a fan of the "faded teal", especially in the links and in the list backgrounds.

Responsive:

* It definitely looks better on smaller screens.
* It would be nice if we could collapse the header items into a menu for really small screens. Right now, the "Install" and "About" buttons wrap.

**Comment by jessicaschilling** [comment]
@Stebalien The header works down to 315px, which AFAIK is narrower than any mainstream smartphone. Are you seeing something otherwise?

The global teal was changed in ipfs-css for reasons of failing WCAG accessibility contrast; see https://github.com/ipfs-shipyard/ipfs-webui/issues/1379#issuecomment-582457581 for details.

**Comment by Stebalien** [comment]
We could still pick a less ugly color.

**Comment by jessicaschilling** [comment]
That’s probably something to take as a discussion within ipfs-css rather than this particular instantiation. Can change links to the bright teal, but please be aware of accessibility caution.

**Comment by jessicaschilling** [comment]
@Stebalien Updated link color to a blue virtually identical to (but AA-compliant) one used in a few other IPFS contexts but not so far included in ipfs-css. If acceptable, will add as a link-specific color to ipfs-css for future use. Please review as time permits -- thank you.

**Comment by Stebalien** [comment]
Much better! Sorry for being so opinionated on this, I just _really_ don't like that color.

**Comment by jessicaschilling** [comment]
@Stebalien Fair enough ... teal-type (green-leaning) blues are REALLY tough to work with from an overall a11y perspective, and I want to make sure that we give overall use of color some very careful consideration as part of the larger-scale a11y analysis to be done in https://github.com/ipfs/ipfs-gui/issues/28. That's also part of a bigger-picture suite of improvements to Desktop/WebUI that we'd ideally focus on in Q3, but in the meantime the GUI team is launching some research/survey work in the next few weeks that'll help inform the best approach. (I also want to do some overall use case/journey mapping work on IPFS helper tools this quarter, but that's going to be balanced against spending my time on more tactical improvements like this one.)

**Comment by RubenKelevra** [comment]
Thanks, looks great!

I was wondering if we could move the PNGs out of the webpage to /ipfs/-links as well. This avoids that the browser have read over the PNG on each page view, but can place it in the cache.

**Comment by jessicaschilling** [comment]
@rubenkelevra You mean the bug report icon? The IPFS logo is already in the larger set of the assets called from the stylesheet.

**Comment by jessicaschilling** [comment]
@RubenKelevra Do you mind filing a separate issue (or PR!) for that one? Ideally we'd like to refactor all those file icons as SVGs that more closely fit the IPFS visual style overall — that would be a good combined effort.

**Pull request merged**
