### PR TITLE
Updates header, adds links

### LINKED ISSUE #1: Add IPFS links to the header
Add links to the index listing header: 
- [ ] What is IPFS?
- [ ] Install IPFS
- [ ] Bug Report icon (linking to https://github.com/ipfs/dir-index-html/issues/)

### PR DESCRIPTION
**Pull request by jessicaschilling**
Changes to `dir-index.html` only (see question below): 
- Adds links and bug report icon requested in #1 
- Updates header color and adds header border
- Updates IPFS logo
- Misc minor visual styling

Note that this still isn't responsive; fixing that is more involved and is part of https://github.com/ipfs/dir-index-html/issues/24. 

**Question:** What's the situation with `dir-index.html` vs `dir-index-uncat.html`? Are we maintaining both of these? If so, would still appreciate a review before duplicating changes to `dir-index-uncat.html`.

Closes #1

### CODE REVIEW

**Comment by jessicaschilling** [comment]
@Stebalien -- do you mind having a look if you have time? Thanks!

**Comment by Stebalien** [comment]
> Question: What's the situation with dir-index.html vs dir-index-uncat.html? Are we maintaining both of these? If so, would still appreciate a review before duplicating changes to dir-index-uncat.html.

We're trying to, at least. We should add a script that generate dir-index.

**Comment by jessicaschilling** [comment]
@stebalien - thanks! Just duplicated the `dir-index.html` changes to `dir-index-uncat.html`. Should be good to go.

**Comment by lidel** [comment]
@jessicaschilling just tested this with go-ipfs 0.5.50-rc3 and looks awesome! :heart: 

Mind updating screenshot in `README.md`? 
I would do it myself but screenshots made on Linux are fugly :sweat:

**Comment by jessicaschilling** [comment]
@lidel Yours to merge: https://github.com/ipfs/dir-index-html/pull/28

**Pull request merged**
